pipeline:
  build: 
    image: openjdk:8
    commands: ./gradlew clean build
  docker:
    image: plugins/gcr
    repo: calm-scarab-217116/sb-drone-demo
    registry: gcr.io
    tags: ["commit_${DRONE_COMMIT}","build_${DRONE_BUILD_NUMBER}", "latest"]
    secrets: [username, password]
    when:
      branch: master

