pipeline:
  build: 
    image: openjdk:8
    commands: ./gradlew clean build
  publish:
    image:  plugins/gcr
    registry: gcr.io
    repo: calm-scarab-217116/sb-drone-demo
    tag:
      - "latest"
      - "commit_${DRONE_COMMIT}"
      - "build_${DRONE_BUILD_NUMBER}"
    secrets: [google_credentials]
    when:
      branch: master
  # deploy:
  #   image: quay.io/honestbee/drone-kubernetes
  #   kubernetes_server: ${kubernetes_api_server}
  #   kubernetes_token: ${kubernetes_api_token}
  #   namespace: dev-space
  #   deployment: sb-drone-demo-deployment
  #   repo: gcr.io/calm-scarab-217116/sb-drone-demo
  #   container: sb-drone-demo
  #   tag: "commit_${DRONE_COMMIT}"
  deploy:
    image: vallard/drone-kube
    template: k8s/deployment.yaml
    namespace: dev-space
    server: ${kubernetes_api_server}
    kubernetes_token: ${kubernetes_api_token}
    
