pipeline:
  build: 
    image: openjdk:8
    commands: ./gradlew clean build
  publish:
    image: plugins/ecr
    repo: 567651206748.dkr.ecr.us-east-1.amazonaws.com/sb-drone-demo
    registry: 567651206748.dkr.ecr.us-east-1.amazonaws.com/sb-drone-demo
    region: us-east-1
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags:
      - "latest"
      - "commit_${DRONE_COMMIT}"
      - "build_${DRONE_BUILD_NUMBER}"
      - "${DRONE_BUILD_NUMBER}"
  
  # refer this https://github.com/kubernetes/kops/blob/master/docs/security.md to get the token.
  # Omit the cert in case self-signed certificate used, --insecure-skip-tls-verify=true will be used to avoid tls
  deploy:
    image: quay.io/hectorqin/drone-kubectl
    kubernetes_template: k8s/deployment.yaml
    kubernetes_namespace: dev-space
    secrets: 
      - kubernetes_server
      - kubernetes_token
      - kubernetes_cert
    when:
      branch: master

