pipeline:
  # build: 
  #   image: openjdk:8
  #   commands: ./gradlew clean build
  # publish:
  #   image:  plugins/gcr
  #   registry: gcr.io
  #   repo: calm-scarab-217116/sb-drone-demo
  #   tag:
  #     - "latest"
  #     - "commit_${DRONE_COMMIT}"
  #     - "build_${DRONE_BUILD_NUMBER}"
  #   secrets: [google_credentials]
  #   when:
  #     branch: master
  #     event: push
  deploy:
    image: sh4d1/drone-kubernetes
    kubernetes_template: .kube.yml
    kubernetes_namespace: dev-space
    secrets: [kubernetes_server, kubernetes_cert, kubernetes_token]
  # deploy:
  #   image: quay.io/honestbee/drone-kubernetes
  #   kubernetes_server: ${kubernetes_api_server}
  #   kubernetes_token: ${kubernetes_api_token}
  #   namespace: dev-space
  #   deployment: sb-drone-demo
  #   repo: gcr.io/calm-scarab-217116/sb-drone-demo
  #   container: sb-drone-demo
  #   tag: "commit_${DRONE_COMMIT}"

  # deploy:
  #   image: vallard/drone-kube
  #   template: k8s/deployment.yaml
  #   namespace: dev-space
  #   server: ${kubernetes_api_server}
  #   kubernetes_token: ${kubernetes_api_token}
    
  # gke:
  #     image: nytimes/drone-gke
  #     zone: us-central1-a
  #     cluster: my-cluster-1
  #     namespace: dev-space
  #     project: calm-scarab-217116
  #     token: >
  #       $$GOOGLE_CREDENTIALS
  #     environment:
  #       - USER=root
  #       - GOOGLE_TOKEN=${google_credentials}
  #     expand_env_vars: true
  #     debug: true
  #     vars:
  #       image: gcr.io/calm-scarab-217116/sb-drone-demo:latest
  #       app: sb-drone-demo
  #       env: dev-space
  #       # user: $${USER}
  #     secrets:
  #       - source: GOOGLE_CREDENTIALS
  #         target: token
  #       # - source: API_TOKEN
  #       #   target: secret_api_token
  #       # - source: P12_CERT
  #       #   target: secret_base64_p12_cert
  #     when:
  #       event: push
  #       branch: master