---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sb-drone-demo-service"
  namespace: "dev-space"
  labels:
    region: "dev"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    region: "dev"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "sb-drone-demo"
  namespace: "dev-space"
  labels:
    app: {{.app}}
    env: {{.env}}
spec:
  replicas: 3
  selector:
    matchLabels:
      region: "dev"
  template:
    metadata:
      labels:
        region: "dev"
    spec:
      containers:
      - name: "sb-drone-demo"
        image: {{.image}}
